# Docker Compose configuration for nginx-proxy setup
# Defines six services: nginx (reverse proxy), python-app1, python-app2, node-app, ruby-app, and php-app

# version: '3.8'

services:
  # Nginx reverse proxy service
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount nginx configuration
      - ./local.conf:/etc/nginx/local.conf:ro  # Mount additional nginx configuration
    depends_on:
      - python-app1
      - python-app2
      - node-app
      - ruby-app
      - php-app

  # Application 1 service
  python-app1:
    build: 
      context: ./app1
      dockerfile: Dockerfile
    expose:
      - "8000"  # Expose port 8000 internally

  # Application 2 service
  python-app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    expose:
      - "8000"  # Expose port 8000 internally
    deploy:
      replicas: 2  # Specify the number of replicas

  # Node.js Application service
  node-app:
    build:
      context: ./app5
      dockerfile: Dockerfile
    expose:
      - "3000"  # Expose port 3000 internally

  # Ruby Application service
  ruby-app:
    build:
      context: ./app3
      dockerfile: Dockerfile
    expose:
      - "8000"  # Expose port 8000 internally

  # PHP Application service
  php-app:
    build:
      context: ./app4
      dockerfile: Dockerfile
    expose:
      - "80"  # Expose port 80 internally