# Docker Compose configuration for nginx-proxy setup
# Defines four services: nginx (reverse proxy), app1, app2, and my-node-app

version: '3.8'

services:
  # Nginx reverse proxy service
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount nginx configuration
    depends_on:
      - app1
      - app2
      - my-node-app

  # Application 1 service
  app1:
    build: 
      context: ./app1
      dockerfile: Dockerfile
    expose:
      - "8000"  # Expose port 8000 internally

  # Application 2 service
  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    expose:
      - "8000"  # Expose port 8000 internally

  # Node.js Application service
  my-node-app:
    build:
      context: ./app5
      dockerfile: Dockerfile
    expose:
      - "3000"  # Expose port 3000 internally