# Docker Compose configuration for traefik setup
# Defines six services: traefik (reverse proxy), python-app1, python-app2, node-app, ruby-app, and php-app

# version: '3.8'

services:
  # Traefik reverse proxy service
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
      - "8081:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Mount docker socket to detect services

  # Application 1 service
  python-app1:
    build: 
      context: ./app1
      dockerfile: Dockerfile
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.python-app1.rule=PathPrefix(`/app1`)"
      - "traefik.http.services.python-app1.loadbalancer.server.port=8000"

  # Application 2 service
  python-app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    expose:
      - "8000"
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.python-app2.rule=PathPrefix(`/app2`)"
      - "traefik.http.services.python-app2.loadbalancer.server.port=8000"

  # Node.js Application service
  node-app:
    build:
      context: ./app5
      dockerfile: Dockerfile
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-app.rule=PathPrefix(`/node`)"
      - "traefik.http.services.node-app.loadbalancer.server.port=3000"

  # Ruby Application service
  ruby-app:
    build:
      context: ./app3
      dockerfile: Dockerfile
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ruby-app.rule=PathPrefix(`/ruby`)"
      - "traefik.http.services.ruby-app.loadbalancer.server.port=8000"

  # PHP Application service
  php-app:
    build:
      context: ./app4
      dockerfile: Dockerfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-app.rule=PathPrefix(`/php`)"
      - "traefik.http.services.php-app.loadbalancer.server.port=80"